[package]
name = "luminol_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.10.3"
dotenv = "0.15.0"
rand = "0.8.5"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "framework", "standard_framework", "http", "cache"] }
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
